name: CI

# CI is run on pull requests and on push to the main branch
on:
  pull_request:
  push:
    branches: [ master, main ]

jobs:
  test:
    # This job is to run the tests
    name: Run tests of elm-test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Run on Mac and Linux, for multiple Node versions
        os: [macos-latest, ubuntu-latest]
        node: ['10', '12', '14', '16']

    env:
      ELM_HOME: '${{ github.workspace }}/elm-home'

    steps:
      # Clone the repository
      - uses: actions/checkout@v2

      # Setup Node JS
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      # Re-use node_modules between runs until package.json changes.
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package.json') }}

      # Re-use ~/.elm between runs until elm.json, elm-tooling.json or
      # review/elm.json changes. The Elm compiler saves downloaded Elm packages
      # to ~/.elm, and elm-tooling saves downloaded tool executables there.
      - name: Cache ~/.elm
        uses: actions/cache@v2
        with:
          path: ~/.elm
          key: elm-${{ hashFiles('elm.json', 'elm-tooling.json', 'review/elm.json') }}

      - name: npm install
        env:
          NO_ELM_TOOLING_INSTALL: 1
        run: npm install

      - name: elm-tooling install
        run: npx --no-install elm-tooling install

      - name: Run the tests
        run: npm test

  check_formatting:
    # This job is to check the formatting of files
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      # Clone the repository
      - uses: actions/checkout@v2

      # Install elm-format
      - name: Install elm-format
        uses: mpizenberg/elm-tooling-action@v1.2
        with:
          cache-key: format-${{ matrix.os }}-node${{ matrix.node }}-0
          cache-restore-key: format-${{ matrix.os }}-node${{ matrix.node }}

      - name: Check formatting
        run: npm run format
